#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Builds editions.json with the FULL content of each PDF edition (all 9
sections, verbatim from the PDF build scripts / extracted PDF text) so the
HTML dashboard can mirror the PDF format exactly rather than a condensed
summary. Run once per edition change, then run build_dashboard.py.
"""
import json

EDITIONS = {}

# ======================================================================
# 2026-07-27 (current) — sourced verbatim from build_report27jul.py
# ======================================================================
EDITIONS["2026-07-27"] = {
    "label": "27 Jul 2026",
    "editionLine": "Daily edition · 27 Jul 2026 intraday · Bloomberg · Singapore 27 Jul AM update",
    "score": 25, "band": "CRISIS", "sequencing": "25 → 25 → 25",
    "sessionNote": "Ninth session at 25",
    "headline": "Note: 27 Jul figures are intraday prints; 24 Jul is now a final close ($91.68 Brent). Restated continuation series (front-month CO2/CL2) in force. Score HOLDS at 25/30 — all six channels unchanged, a NINTH session at 25 — but the weekend flipped the board's direction. The US halted airstrikes after 13 consecutive nights — the first pause in two weeks; the Pentagon calls the campaign ‘on a hold’ while the naval blockade stays fully operational — and Iran–Oman technical talks on the strait are described by Tehran as ‘productive’. The tape is unwinding war premium at the fastest pace since the 2–3 Jul deal-hope window: Brent closed Friday $91.68 (–$2.58) and prints $87.88 this morning (–$3.80 d/d; $6.38 off the 23 Jul $94.26 peak close), the active COA prints $92.47 after touching $100.69 Thursday, TTF prints €58.50 (–€5.08) after a record €63.58 Friday close, the 10Y prints 4.6365% — back below the 4.65% Stage-4 leg after three consecutive closes above — and MOVE fell 80.08 → 76.82, snapping five straight rises. But the de-escalation is one-legged: while Washington paused, the Houthis put missiles and drones into Aramco's 400 kb/d Jizan refinery (satellite thermal data confirms large fires) and attacked Yanbu — the terminal carrying ~92% of Saudi seaborne crude exports in June — where air defences intercepted both missiles; Saudi Arabia struck back inside Yemen, its first direct combat entry of the war. And Friday's close moved two triggers to within a whisker even as crude fell: 5Y5Y closed 2.2877% (+8.8 bp), 1.2 bp from the US-inflation→5 trigger — the closest any market trigger has stood all war — and AAA gasoline's latest confirmed print $4.73 (23 Jul) is 2 cents from political→5 on an eighth consecutive rise. No trigger fired on a confirmed close, so no channel moved; with both event channels maxed, the hold is an artifact of the scale. FOMC Tuesday–Wednesday is the week's re-arming catalyst. Sequencing 25 → 25 → 25.",

    "tape": {
        "note": "27 Jul 2026 readings are intraday prints; 24 Jul and earlier are final closes (restated continuation series; front-month CO2/CL2). d/d deltas are 27 Jul intraday vs 24 Jul close; w/w deltas are vs 20 Jul close.",
        "oilGasHeader": ["Benchmark", "Intraday 27 Jul", "Δ d/d", "Δ vs pre-war close (27 Feb)", "BBG ticker"],
        "oilGas": [
            ["Brent front-month", "$87.88 /bbl (H 88.95 / L 85.50)", "–$3.80 (+$0.74 w/w)", "from $72.48 (+21.2%) — ~$15.4/bbl premium; the war-premium unwind has retraced the entire embargo-week spike — w/w is back to +$0.74; active COA prints $92.47", "CO2 Comdty (Close)"],
            ["Brent · 24 Jul close (final)", "$91.68 /bbl (–$1.81 vs my 24 Jul intraday $93.49)", "–$2.58 d/d — first daily decline in five sessions; tape came OFF through the US session", "$3.32 below the $95 trigger on a close basis — the gap re-widened from Thursday's 74 cents; active COA closed $96.78", "CO2 Comdty"],
            ["WTI front-month", "$81.60 /bbl", "–$3.55 (–$0.88 w/w)", "from $67.02 (+21.8%) — the CL2 artifact persists: 24 Jul CL2 close $85.15 vs active CLA $89.31; CLA prints $85.10 intraday", "CL2 Comdty"],
            ["Brent–WTI spread", "$6.28 /bbl", "narrowed", "~$7.4 on the active contracts", "derived"],
            ["Henry Hub natural gas", "$2.810 /MMBtu", "–$0.061 (–$0.05 w/w)", "from $3.06 (–8.3%) — US gas BELOW pre-war; not Hormuz-exposed", "NGA Comdty"],
            ["TTF Dutch gas (active)", "€58.50 /MWh", "–€5.08 (–€0.24 w/w)", "from €31.23 (+87.3%) — the 24 Jul close €63.58 was a NEW war-era record and a second close above the doubling line (€62.45); Monday's tape gave the whole embargo-week move back", "TZTA Comdty"],
            ["Japan/Asia LNG (24 Jul close — FRESH print)", "¥3,593", "–¥8 vs the ¥3,601 record", "from ¥1,669 (+115.3%) — eased fractionally off the war-era record; no 27 Jul print (flagged, not carried)", "JGLA Comdty"],
        ],
        "ustNote": "27 Jul 2026 yields are intraday. d/d deltas are vs the 24 Jul close; w/w vs 20 Jul. The 10Y Stage-4 leg held for THREE consecutive closes (4.6545%, 4.6932%, 4.6771%) but prints BELOW its 4.65% line this morning; the 30Y leg is 4.3 bp away on a close basis, 7.8 bp intraday — Threshold B is disarming on the rally.",
        "ustHeader": ["Tenor", "Yield (%) — intraday 27 Jul", "Δ d/d (bp)", "Δ w/w (bp)", "Δ vs pre-war (bp)", "BBG ticker"],
        "ust": [
            ["2-year UST", "4.30", "–3.2", "+9.2", "+92 (from 3.37%)", "USGG2YR Index"],
            ["5-year UST", "4.39", "–3.9", "+6.5", "+88 (from 3.50%)", "USGG5YR Index"],
            ["10-year UST", "4.64", "–4.1", "+4.5", "+70 (from 3.94%) — 24 Jul close 4.6771%, a THIRD consecutive close above the 4.65% Stage-4 leg; the intraday print is back below the line for the first time in four sessions", "USGG10YR Index"],
            ["30-year UST", "5.12", "–3.6", "+0.9", "+51 (from 4.61%) — 24 Jul close 5.1574%, 4.3 bp below the 5.20% Stage-4 leg; the intraday gap is 7.8 bp and WIDENING for the first time in a week", "USGG30YR Index"],
            ["2s10s spread", "+34 bp", "–0.7", "–4.3", "–22 (flatter)", "USYC2Y10 Index"],
            ["10Y breakeven inflation", "2.245", "–0.1", "–1.1", "–1.2 (from 2.257%) — the 24 Jul close 2.2463% slipped BACK BELOW the pre-war anchor after three closes above", "USGGBE10 Index"],
            ["5Y5Y forward inflation", "2.28", "–0.8", "+7.4", "+13.8 (from 2.14%) — the 24 Jul close 2.2877% jumped +8.8 bp to 1.2 bp below the →5 trigger — the war's closest approach; intraday 2.2799%", "USGG5Y5Y Index"],
            ["SOFR (lagged print, 23 Jul)", "3.64", "—", "—", "series lags", "SOFRRATE Index"],
        ],
        "crossHeader": ["Gauge", "Latest", "As of", "Δ vs pre-war", "Interpretation"],
        "cross": [
            ["DXY", "101.20", "27 Jul intraday", "+3.59 (from 97.61)", "Marginally softer on the de-escalation tape; still no haven bid; the dollar is not the stress valve."],
            ["MOVE", "76.82", "24 Jul close (27 Jul lagged)", "+3.44 (from 73.38)", "SNAPPED the five-session rise (80.08 → 76.82) as strikes paused — but still above the 75 downgrade leg by 1.8 pts; both Treasury legs continue to fail."],
            ["VIX", "18.58", "24 Jul close (27 Jul lagged)", "–1.28 (from 19.86)", "Eased with the pause headlines; the 23 Jul tanker-attack snap (+2.06) partially retained."],
            ["AAA gasoline", "$4.73 /gal", "23 Jul print (latest; 24–27 Jul pending)", "+$1.21 (from $3.52, +34%)", "The political-stress reference (pre-war $3.52, peak $5.18). EIGHTH consecutive rise; 2 cents below the $4.75 threshold — the next confirmed print lands at or through it at the recent 1–4c pace."],
            ["DOE gasoline", "$4.001 /gal", "20 Jul weekly print", "~+$1.06 (from ~$2.94, +36%)", "First $4-handle since 15 Jun; the next weekly print lands TODAY (Monday 27 Jul) — corroboration for the pending AAA trigger test."],
        ],
        "gasChartNote": "AUTMUSAG (AAA all-grades retail pump, daily) is the political-stress score reference (pre-war $3.52, peak $5.18, latest $4.73 on 23 Jul); USRFRUSA (DOE regular-grade retail spot, weekly) is the complementary gauge (pre-war ~$2.94, peak $4.50, latest $4.001 on 20 Jul; next print today). The AAA series has risen in eight consecutive prints and sits 2 cents from the $4.75 political→5 threshold; the 24–27 Jul prints are pending and the channel is evaluated on confirmed prints only — the score holds until the data lands. Whether the crude pullback (–$6.38 off the peak close) arrives at the pump before the trigger prints is now the channel's live question: retail lags crude by 1–2 weeks in both directions.",
        "straitHeader": ["Indicator", "Current reading", "Source"],
        "strait": [
            ["Strait closed · day ~149", "Closed to commercial traffic (blockade regime since 28 Feb war start); US naval blockade plus escort operation (~900 escorted transits, ~450m bbl since early May, per CENTCOM; 12 commercial vessels redirected 26 Jul); Iran conditions transit on its own coordination and fees.", "CENTCOM / maritime trackers"],
            ["US strikes ON HOLD after 13 consecutive nights", "The Pentagon announced no new strikes for the first time in two weeks (25 Jul) and describes the campaign as ‘on a hold’ to let diplomacy progress (26 Jul); the naval blockade remains fully operational; the administration says the Cabinet is ‘locked and loaded’ to resume if Iran refuses nuclear concessions. Iran–Oman technical and political consultations on the strait are described by Tehran as ‘productive’; Iranian officials say transit conditions are unchanged.", "DoD / CNN / WaPo / Fox / Washington Institute"],
            ["Houthi strikes reach Saudi SOIL — Jizan burns, Yanbu intercepted; Riyadh enters the war", "At dawn 25 Jul the Houthis fired what their spokesman calls ‘dozens of ballistic missiles and drones’ (Tier 3 claim) at Aramco's 400 kb/d Jizan refinery — satellite thermal data and regional media confirm multiple large fires and at least five explosions — and two ballistic missiles at Yanbu, both intercepted. Yanbu handled ~92% of Saudi seaborne crude exports in June. Saudi Arabia struck Houthi targets inside Yemen the same day — its first direct combat entry of the war.", "TechTimes citing NASA FIRMS / CNBC / TWZ / Saree statement (Tier 3)"],
            ["Mediation — pause opens a window", "The Qatar/Egypt/Pakistan/Oman 10-day framework remains tabled; Pakistan, with Chinese support, is pushing to revive US–Iran negotiations; Netanyahu meets Trump at the White House Wednesday — the wildcard for whether the pause hardens into a ceasefire or resets to strikes.", "Axios / Bloomberg / Al Jazeera / MEMO"],
        ],
    },

    "analysis": {
        "intro": "The US economic shock holds at 25/30 for a ninth session, but the composition inverted over the weekend: the geopolitical tape eased — first US strike pause in two weeks, ‘productive’ Oman channel, crude and gas giving back the embargo-week spike — while the inflation leg tightened to the closest trigger approach of the war. 5Y5Y closed Friday at 2.2877% (+8.8 bp on the day crude FELL $2.58), 1.2 bp from the 2.30% US-inflation→5 trigger, and AAA gasoline's eighth consecutive rise put it 2 cents from political→5 with four prints pending. That divergence — spot energy down, forward inflation compensation up — says the market has moved from pricing the shock to pricing its pass-through, three days before a FOMC that meets with May CPI at 4.2% and Chair Warsh on record that inflation remains too high. Treasury stress eased without releasing: MOVE snapped its five-session rise but holds above the 75 leg, the 10Y slipped back below its Stage-4 line intraday, and the 30Y cushion over the 5.00% downgrade leg is still 15.7 bp. No trigger fired on a confirmed close; nothing moved.",
        "bondYieldNote": "27 Jul yields are intraday; d/d vs 24 Jul close, w/w vs 20 Jul. No channel moved; score held at 25.",
        "bondYield": [
            {"title": "(i) Treasury — held at 5; the downgrade legs still fail, but the margin is narrowing for the first time in a week.", "text": "The 30Y closed 24 Jul at 5.1574% — 15.7 bp above the 5.00% downgrade leg — and prints 5.1218% this morning; MOVE closed 76.82, snapping five consecutive rises but holding 1.8 pts above its 75 leg. Both legs must clear simultaneously and sustain to downgrade — neither is close yet, but this is the first session since 16 Jul in which both moved TOWARD release together. The FOMC (28–29 Jul) is the binary: markets price roughly a two-thirds probability of a hold with a meaningful hike tail, and Warsh's Sintra line — inflation ‘remains too high’ — cuts against a dovish read. A hawkish outcome re-arms the long end; a genuine multi-week pause in strikes would do the opposite."},
            {"title": "(ii) Inflation anchor — held at 4 by 1.2 basis points; the war's closest trigger approach.", "text": "5Y5Y closed 2.2877% — +8.8 bp on a day Brent fell $2.58 — and prints 2.2799% intraday (2.0 bp from the line). The advance is no longer tracking spot crude: it is pass-through pricing — eight straight AAA gasoline rises, May CPI at 4.2%, and pre-FOMC positioning. The 10Y breakeven moved the other way, closing 2.2463%, back below its pre-war anchor after three closes above — the curve is pricing medium-term persistence rather than a near-term spike. One close above 2.30% starts the clock; a second consecutive close confirms and takes the channel to 5/5 and the score to 26. The downgrade (sustained at/below the 2.142% anchor) is not in play."},
            {"title": "(iii) Oil — held at 2; the gap re-widened from 74 cents to $3.32 on the close, $7.12 intraday.", "text": "Friday's $91.68 close was the first daily decline in five sessions and this morning's $87.88 print has retraced the entire embargo-week spike — w/w is back to +$0.74. The driver is the strike pause and the Oman channel, and it outweighed a weekend in which the Houthis hit Saudi soil for the first time — because Jizan is a refinery (products, domestic) not a crude-export node, and the Yanbu intercepts left the ~92% export corridor physically intact. The active COA prints $92.47 after Thursday's $100.69 close — the triple-digit board lasted one session. The two-close rule kept the channel at 2 through the entire $95 approach and now spares it a whipsaw on the way down; the downgrade to 1 needs a mediated pause plus a close at or below the $72.48 anchor — far away. (Supply crosscurrents cut both ways: OPEC+ approved higher output quotas, while drone strikes again halted loading at Russia's CPC Black Sea terminal.)"},
        ],
        "stage4Note": "Stage 4 is a credit/auction event. Threshold B was 4.1 bp from completion on Thursday's close; the weekend rally is disarming it — the 10Y leg prints below its line this morning.",
        "stage4": [
            {"title": "Threshold A · 13 May 30Y auction.", "text": "Historical. Cleared at 5.050%; the 9 Jul re-opening cleared 5.06% with a 0.3 bp stop-through. The 30Y still trades well above both marks; the FOMC statement and presser (Wednesday) are this week's long-duration pricing events — no coupon supply until the August refunding."},
            {"title": "Threshold B · 30Y above 5.20% with 10Y above 4.65%.", "text": "The near-completion of Thursday (30Y 4.1 bp away, 10Y leg sustained on three closes) is unwinding: the 30Y closed Friday 5.1574% (4.3 bp below its leg) and prints 5.1218% — 7.8 bp below — while the 10Y prints 4.6365%, BELOW its line for the first time in four sessions. The 10Y leg's ‘sustained’ status survives one intraday slip but not a string of sub-4.65% closes — two consecutive closes below would reset it. B re-arms on a hawkish FOMC, a strike resumption, or a Yanbu re-attack that lands; it disarms fully if the pause holds through the week."},
            {"title": "Threshold C · MOVE above 130.", "text": "Far off and receding — 76.82 after snapping the five-rise streak at 80.08. The vol bid was war-premium, and it is coming out with the pause; FOMC week puts a floor under it."},
        ],
        "crossAsset": "The weekend produced the cleanest risk-reversal pattern of the month: crude, European gas, long yields and rates vol all lower together on the strike pause, with the dollar drifting (101.20) and no haven bid — an orderly unwind, not a flight. The exceptions are the tell: 5Y5Y rose +8.8 bp into the falling-crude tape and AAA gasoline printed an eighth straight rise — the inflation complex is now running on realized pass-through rather than spot-barrel risk, which is exactly the configuration that makes Wednesday's FOMC binding. The gas complex remains the war's scoreboard: TTF set a war-era record close €63.58 Friday (a second close above the doubling line) before Monday's €5 give-back, Asia LNG printed ¥3,593 fresh — ¥8 off its record — and US Henry Hub sits 8.3% BELOW pre-war: still a Hormuz/LNG-routing shock, not a global-energy shock. Watch whether the pump lags the crude pullback long enough for the political trigger to fire anyway — retail gasoline follows crude down with a 1–2 week lag, and the trigger is 2 cents away with four prints pending.",
    },

    "channels": [
        {"name": "Maritime denial", "score": 5, "state": "max", "rationale": "Held at 5 (max). Strait closed to commercial traffic, day ~149; transits ~17% of typical (15 vs 88/day); 445–540 anchored (revised basis); 88 tankers AIS-dark in 24h vs a 63.5 average; war-risk ~8×, VLCC ~$2.5m; six P&I clubs withdrawn; 8 of 9 major carriers rerouting via the Cape ($600–1,200/TEU surcharges). No verified reopening — Iranian officials say transit conditions are unchanged despite the talks.", "upgrade": "at max.", "downgrade": "verified reopening (escorted convoys) with traffic above 25% of normal for 10 sessions → to 3–4."},
        {"name": "Oil price shock", "score": 2, "state": "hold", "rationale": "Held at 2 — and the gap re-widened. 24 Jul close $91.68 (–$2.58, first decline in five sessions), $3.32 below the $95 trigger; intraday $87.88, $7.12 below. The $95 approach died at 74 cents on Thursday's close; the two-close rule prevented a whipsaw in both directions. Active COA prints $92.47 off a one-session $100.69.", "upgrade": "Brent above $95 sustained → to 3.", "downgrade": "mediated pause + close back at/below the $72.48 anchor → to 1."},
        {"name": "US inflation impulse", "score": 4, "state": "hold", "rationale": "Held at 4 — by 1.2 basis points, the war's closest trigger approach. 5Y5Y closed 2.2877% (+8.8 bp on a falling-crude day); intraday 2.2799%. The advance is pass-through pricing, not spot-crude beta: 10Y BE closed back BELOW its pre-war anchor (2.2463%) while the pump rose an eighth straight print. One close above 2.30% starts the clock.", "upgrade": "5Y5Y sustained above 2.30% → to 5.", "downgrade": "5Y5Y sustained at/below the 2.142% pre-war anchor → to 3."},
        {"name": "Treasury stress", "score": 5, "state": "max", "rationale": "Held at 5 — both downgrade legs still fail, but the margin narrowed for the first time in a week. 30Y closed 5.1574% (15.7 bp above the 5.00% leg), prints 5.1218%; MOVE 76.82, snapping five straight rises, 1.8 above its 75 leg. Downgrade needs BOTH legs sustained — not close yet; FOMC decides the direction.", "upgrade": "at max.", "downgrade": "30Y close under 5.00% with MOVE under 75 sustained → to 4."},
        {"name": "Political stress", "score": 4, "state": "hold", "rationale": "Held at 4 — two cents from the trigger. AAA $4.73 (23 Jul print, latest confirmed) — EIGHTH consecutive rise; DOE weekly $4.001 with the next print landing today. The 24–27 Jul prints are pending; at the recent 1–4c pace the next print lands at or through $4.75. Evaluated on confirmed prints only.", "upgrade": "gasoline above $4.75 sustained → to 5.", "downgrade": "toward the $3.52 pre-war level → to 3."},
        {"name": "Escalation risk", "score": 5, "state": "max", "rationale": "Held at 5 (max). The US strike pause is real but reversible (‘on a hold’; ‘locked and loaded’ to resume) — and the war widened anyway: Houthi missiles hit Saudi soil (Jizan ablaze, Yanbu intercepted) and Saudi Arabia entered direct combat in Yemen. A downgrade needs a mediated stand-down plus resumed talks — the pause is a necessary first step, not yet the event.", "upgrade": "at max.", "downgrade": "mediated stand-down + talks resume → to 4–3."},
    ],
    "scoreTotal": "CRISIS band — ninth session at 25, with the board's tension inverted: the geopolitical tape eased while two market triggers closed to a whisker — US-inflation→5 is 1.2 bp away on a close basis, political→5 is 2 cents on a pending print. Oil→3 receded to $3.32. With both event channels maxed, only market channels can move the score — in either direction.",

    "whatsChanged": {
        "title": "4 · What's changed since the last edition (24 Jul → 27 Jul AM)",
        "items": [
            "Score holds at 25/30 for a ninth session — through the war's first US strike pause. No channel moved; the direction of travel inverted: geopolitics eased, the inflation triggers tightened. Source: Bloomberg.",
            "The US halted airstrikes after 13 consecutive nights. First no-strike announcement in two weeks (25 Jul); the Pentagon calls the campaign ‘on a hold’ to let diplomacy progress (26 Jul) while the naval blockade stays fully operational and the Cabinet is described as ‘locked and loaded’ to resume. Iran–Oman technical talks: ‘productive’ (Tehran). Source: DoD / CNN / WaPo / Fox.",
            "The Houthis hit Saudi soil — and Riyadh entered the war. Dawn-Saturday strikes set Aramco's 400 kb/d Jizan refinery ablaze (satellite thermal confirmation; at least five explosions) and sent two ballistic missiles at Yanbu — both intercepted, the ~92% export corridor intact. Saudi Arabia struck Houthi targets in Yemen the same day, its first direct combat of the war. Source: TechTimes citing NASA FIRMS / CNBC / TWZ.",
            "The war premium is unwinding at the fastest pace since early July. Brent: $94.26 (23 Jul close) → $91.68 (24 Jul close) → $87.88 intraday; the active COA gave back its $100-handle in one session ($100.69 → $92.47 print). TTF fell €5.08 off Friday's record €63.58 close. Source: Bloomberg.",
            "5Y5Y jumped to 1.2 bp from the →5 trigger — on a falling-crude day. The 24 Jul close 2.2877% (+8.8 bp) is the war's closest trigger approach; the 10Y breakeven went the other way, closing back below its pre-war anchor. The inflation complex is pricing pass-through, not spot. Source: Bloomberg.",
            "The Treasury complex stepped back from Stage 4. MOVE snapped five straight rises (80.08 → 76.82); the 10Y prints below its 4.65% Stage-4 leg after three closes above; the 30Y intraday gap to 5.20% widened to 7.8 bp. Source: Bloomberg.",
            "Gasoline: an eighth consecutive rise, 2 cents from the trigger. The 23 Jul AAA print landed at $4.73; the 24–27 Jul prints are pending and the DOE weekly lands today. Source: AAA / Bloomberg.",
            "Supply crosscurrents: OPEC+ approved increased output quotas; drone strikes again halted loading at Russia's CPC Caspian terminal. Source: Bloomberg.",
        ],
    },

    "scenarios": [
        {"name": "Return to full war", "p": 33, "desc": "Still the modal path, but no longer strengthening: the pause is explicitly reversible (‘locked and loaded’), Iran has made no nuclear concession, and Netanyahu's Wednesday visit could reset Washington to escalation. A resumption after a failed pause would likely come wider and harder.", "path": "Brent $105–140; MOVE above 90; oil to 3–4, political to 5, US-inflation to 5; score 28–30."},
        {"name": "Contained but violent — blockaded stalemate", "p": 19, "desc": "Strikes resume at lower intensity or sputter; escort-only transits; bypass pipelines keep capping crude. The equilibrium took direct fire this weekend — Jizan burned — but the Yanbu intercepts showed the bypass can be defended.", "path": "Brent $88–96; MOVE 76–86; risk premium $16–24/bbl; score 25–26 as political→5 lands."},
        {"name": "Deal collapse — MoU formally lapses", "p": 19, "desc": "The 10-day framework is rejected or expires; sanctions harden; the strait stays shut; fighting persists without full-war targeting. The pause makes formal collapse marginally less likely this week but the framework remains unaccepted.", "path": "Brent $92–108; oil to 3; 30Y back above 5.15% toward the 5.20% leg; score 26–27."},
        {"name": "Regional relapse — Gulf energy infrastructure hit", "p": 15, "desc": "The ship-to-shore step HAPPENED this weekend — Jizan is the first Aramco facility burned by the embargo campaign; only the Yanbu intercepts kept crude exports whole. A hit that lands on Yanbu, the East–West line, or Abqaiq/Ras Tanura is now a demonstrated capability, not a hypothesis — and Saudi entry into Yemen invites the retry.", "path": "Brent $150+; emergency policy; HY spreads above 500 bp; score 29–30."},
        {"name": "Mediated pause — the ceasefire sticks", "p": 14, "desc": "The strongest version of this scenario all war: a real multi-night strike pause, a ‘productive’ Oman channel, Pakistan–China mediation, and a US administration explicitly framing the pause as space for talks. Needs Iran to move on the nuclear file and the Houthi front to stand down — neither yet visible.", "path": "Brent $74–86; MOVE under 70; Treasury→4, US-inflation→3, escalation→4; score falls toward 20–22."},
    ],
    "scenarioShift": "Probability shifts from the 24 Jul edition: mediated pause +5 (9→14) — the first actual strike pause of the war plus a functioning Oman channel is the strongest de-escalation signal since the interim deal; full war –5 (38→33) — still modal, but the pause and the talks cut against imminent expansion; regional relapse +3 (12→15) — the embargo campaign reached Saudi shore infrastructure and Saudi Arabia entered direct combat; contained-but-violent –2 (21→19) and deal collapse –1 (20→19). Driver: the same weekend delivered the war's first strike pause AND its first strike on Aramco soil — the distribution widened at both ends.",

    "watchlist": [
        "US-inflation →5 (5Y5Y above 2.30% sustained) — 1.2 bp; the closest trigger on the board. Friday's +8.8 bp close means one ordinary session crosses it; Wednesday's FOMC is the catalyst in both directions. First close above starts the clock; the second confirms and the score goes to 26.",
        "Political →5 ($4.75) — 2 cents, four prints pending. Eight consecutive AAA rises; the DOE weekly lands today. The open question is whether the crude pullback reaches the pump before the trigger fires — retail lags crude by 1–2 weeks, so the near-term prints likely still rise.",
        "FOMC · Tuesday–Wednesday 28–29 Jul. Markets price roughly two-thirds for a hold with a hike tail; May CPI 4.2%; Warsh: inflation ‘remains too high’. A hawkish hold re-arms Stage-4 B and the long end; any dovish surprise accelerates the Treasury-channel release path (30Y under 5.00% with MOVE under 75 — currently 15.7 bp and 1.8 pts away).",
        "Does the pause hold a fourth night? ‘If it turns into a multiday pause, that'll be something significant’ (Singh, Washington Institute). A resumption — especially post-Netanyahu — reprices the whole weekend unwind back in; the blockade never stopped.",
        "Yanbu re-attack risk — the demonstrated tail. Jizan proved reach; Yanbu's intercepts held once. A landed hit on the ~92% export corridor is the regional-relapse trigger and reprices crude, breakevens and bond vol together, at full amplitude.",
        "Stage-4 Threshold B — disarming, not disarmed. The 10Y leg needs two closes below 4.65% to reset; the 30Y sits 4.3 bp (close) / 7.8 bp (intraday) from its leg. One hawkish FOMC session or one strike headline re-completes the setup.",
        "Gas complex — records behind, give-back in front. TTF €58.50 after the record €63.58 close; Asia LNG ¥3,593 fresh, ¥8 off record; verify the next JGLA print — never carry.",
    ],

    "sourceLog": {
        "tier1Market": "Bloomberg Terminal extract (US Iran BBG Data.xlsx, restated front-month continuation series). Tickers: CO2/CL2 Comdty (Brent/WTI front-month; the CL2 artifact persists — CL2 closed $85.15 vs active CLA $89.31; WTI is read off the active board); COA/CLA Comdty (active, unscored — COA closed $96.78, prints $92.47); NGA/TZTA/JGLA Comdty (JGLA printed FRESH 24 Jul at ¥3,593, ¥8 off the record; no 27 Jul print); USGG2YR/5YR/10YR/20YR/30YR Index; USYC2Y10; USGGBE10 (24 Jul close 2.2463 — back below the pre-war anchor); USGG5Y5Y (24 Jul close 2.2877 — 1.2 bp from the →5 trigger); SOFRRATE (lagged, 23 Jul); MOVE and VIX (24 Jul closes 76.82 / 18.58; 27 Jul lagged, carried and labelled); DXY; AUTMUSAG (AAA pump — score reference; latest print 23 Jul $4.73; 24–27 Jul pending) and USRFRUSA (DOE regular spot, weekly — corroboration; 20 Jul print $4.001; next print due today).",
        "tier1News": "US DoD / CENTCOM via CNN, Washington Post and Fox (no new strikes announced 25 Jul — first in two weeks; campaign ‘on a hold’ 26 Jul; blockade fully operational; 12 commercial vessels redirected; ‘locked and loaded’ framing), Washington Institute for Near East Policy (Michael Singh on the significance of a multiday pause), CNBC (Saudi strikes on Houthi targets in Yemen after the tanker attacks), TWZ / Seatrade / The National (Houthi tanker campaign context), TechTimes citing NASA FIRMS satellite thermal data (Jizan refinery fires; Yanbu intercepts; ~92% June export share via Yanbu), Al Jazeera / Middle East Monitor (Netanyahu at the White House this week), Bloomberg / TradingEconomics (Pakistan–China push to revive negotiations; OPEC+ quota increase; CPC terminal loading halted by drones; Friday oil-market wrap), straits.live / Windward / IMF PortWatch (day count, transits 15 vs 88/day — ~17% of typical, 19 Jul count; 445–540 anchored on a revised basis; 88 AIS-dark in 24h vs 63.5 avg; ~8× war-risk cover; six P&I withdrawals; 8-of-9-carrier disruption with $600–1,200/TEU surcharges), Federal Reserve calendar and market pricing (FOMC 28–29 Jul; ~two-thirds hold; May CPI 4.2%; Warsh Sintra remarks).",
        "tier3": "The Houthi military statement (Brig. Gen. Yahya Saree) claiming ‘dozens of ballistic missiles and drones’ against Jizan and Yanbu is a combatant claim — the fires are independently corroborated by satellite thermal data; the munition counts are not. The Iranian claim that the IRGC Quds Force commander urged Saudi Arabia to lift the Yemen blockade, and Iranian officials' characterisation of the Oman talks, are labelled Tier 3 / official-source and are not used for any scoring decision. IRNA, Mehr, Press TV used only with explicit role labels.",
    },

    "protocol": [
        {"step": "Refresh the Bloomberg extract", "detail": "Parse the latest dated row (27 Jul) as intraday; reclassify 24 Jul as a final close; re-map columns via the robust scan (front-month CO2/CL2; both gasoline series; JGLA checked fresh — printed 24 Jul ¥3,593, no 27 Jul print, flagged not carried; MOVE/VIX 27 Jul lagged, 24 Jul closes carried and labelled; SOFR lagged 23 Jul)."},
        {"step": "Recompute deltas", "detail": "d/d vs the 24 Jul close; w/w vs the close five trading sessions back (20 Jul this edition); vs-pre-war vs the 27 Feb 2026 anchor (re-verified, unchanged)."},
        {"step": "Re-evaluate the six channels", "detail": "Market channels move on confirmed closes only — all held: oil 2 (close $91.68, gap re-widened to $3.32); Treasury 5 (30Y 5.1574% above 5.00%; MOVE 76.82 above 75); US-inflation 4 (5Y5Y 2.2877%, 1.2 bp under 2.30%); political 4 (AAA $4.73 confirmed, 2c under $4.75). Maritime/escalation event-based, both maxed — the strike pause is not yet a mediated stand-down."},
        {"step": "Reconcile against the prior edition", "detail": "The US session took the tape DOWN through the Asia snapshot for the first time since 9 Jul on the crude leg: Brent 24 Jul intraday $93.49 → close $91.68 (–$1.81); 10Y 4.70% → 4.6771%; 30Y 5.17% → 5.1574%; MOVE 80.08 (carried) → 76.82 close; but TTF €61.96 → €63.58 record close (+€1.62) and 5Y5Y 2.2035% → 2.2877% (+8.4 bp) went the other way."},
        {"step": "Update scenarios and watchlist", "detail": "Re-rank catalysts: US-inflation→5 (1.2 bp — now first in line), political→5 (2c, four prints pending, DOE today), FOMC 28–29 Jul (hold ~two-thirds priced), pause durability / Netanyahu Wednesday, Yanbu re-attack; mediated pause 9→14, full war 38→33 still modal."},
    ],

    "methodology": {
        "scale": "Six transmission channels (maritime denial, oil price shock, US inflation impulse, Treasury stress, political stress, escalation risk), each 0–5, summed to 0–30. Bands: 0–7 watch · 8–14 stress · 15–21 systemic-risk watch · 22–30 crisis. Market/economic channels move only on a confirmed close through a trigger; escalation-risk is event-based. Hysteresis note: upgrades fire on a sustained break; downgrades only on a sustained reversal past a wider threshold — deliberately, to avoid whipsawing. The discipline cut both ways this cycle: the two-close rule kept oil at 2 through Thursday's intraday pierce of $95, and it now prevents any reflexive downgrade on this morning's $87.88 print — the oil downgrade to 1 additionally requires a mediated pause and a close at or below the $72.48 anchor. Treasury remains at 5 because both downgrade legs (30Y under 5.00%, MOVE under 75, sustained together) still fail — by 15.7 bp and 1.8 pts on the 24 Jul close. Scale cap: maritime and escalation are both at 5/5, so neither the weekend's strike pause (not yet a mediated stand-down) nor the Jizan/Yanbu attacks (already-maxed channels) can move the score — only the four market channels can, in either direction. A flat 25 must not be read as stability: this edition, it conceals the largest two-day de-escalation repricing and the closest trigger approach of the war, simultaneously.",
        "gasoline": "Political-stress is scored on AUTMUSAG (AAA all-grades retail pump; pre-war $3.52, peak $5.18, latest confirmed print $4.73 on 23 Jul — an eighth consecutive rise) for continuity; the 24–27 Jul prints are pending in the extract and the channel holds until they are confirmed. USRFRUSA (DOE regular-grade retail spot; pre-war ~$2.94, peak $4.50, latest $4.001 on 20 Jul; next print today, Monday 27 Jul) is tracked alongside. See the chart in section 1.",
        "anchor": "Brent $72.48; WTI $67.02; 2Y 3.375%; 5Y 3.502%; 10Y 3.938%; 30Y 4.611%; 2s10s +55.64 bp; 5Y5Y 2.142%; 10Y BE 2.257%; MOVE 73.38; VIX 19.86; DXY 97.608; gasoline (AAA) $3.52; Henry Hub $3.06; TTF €31.23; Asia LNG ¥1,669. (Re-verified — unchanged.) Brent +21.2%, WTI +21.8%, TTF +87.3%, Asia LNG +115.3% (24 Jul print); the 30Y (+51 bp), 10Y (+70 bp), 5Y5Y (+13.8 bp), MOVE (+3.44) and DXY (+3.59) sit above their anchors; the 10Y breakeven (–1.2 bp) slipped back below its anchor this session, and VIX and US Henry Hub remain below pre-war — the Hormuz/LNG-routing signature intact.",
        "intraday": "The latest dated row is a Singapore-AM intraday snapshot; US-hours trading and headlines set the close (recent reconciliation gaps on Brent: +$2.46, –$0.90, +$1.91, +$0.60, +$3.10, –$1.81 — the 24 Jul session was the first since 9 Jul to close the crude tape BELOW the Asia snapshot). Monday-edition note: MOVE and VIX carry the 24 Jul closes, labelled; the UST curve printed live this morning. The CL2 WTI series remains flagged as a data artifact against the active CLA contract; WTI levels are read off the active board pending resolution. Market-channel triggers are evaluated on confirmed closes; escalation-risk is event-based. Absolute levels use the restated continuation series and are not directly comparable with pre-restatement editions, though the directional analysis is continuous.",
    },
}

# ======================================================================
# 2026-07-24 (previous) — sourced verbatim from the archived PDF's text
# ======================================================================
EDITIONS["2026-07-24"] = {
    "label": "24 Jul 2026",
    "editionLine": "Daily edition · 24 Jul 2026 intraday · Bloomberg · Singapore 24 Jul AM update",
    "score": 25, "band": "CRISIS", "sequencing": "25 → 25 → 25",
    "sessionNote": "Eighth session at 25",
    "headline": "Note: 24 Jul figures are intraday prints; 23 Jul is now a final close ($94.26 Brent). Restated continuation series (front-month CO2/CL2) in force. Score HOLDS at 25/30 — all six channels unchanged, an eighth session at 25 — but the 23 Jul session was the war's most violent single-day repricing in seven weeks. Brent closed $94.26, the first $94-handle close since 4 Jun (+$4.08 d/d, the largest daily close-to-close gain since early June), after the intraday high $95.30 PIERCED the $95 oil→3 trigger level — on the close-basis rule no trigger fired, and the gap to the trigger is now 74 cents; the ACTIVE contract (COA) closed $100.69, the first triple-digit close on the unscored board since 22 May. The driver was kinetic: the Houthi embargo turned from declaration to attack — missiles and drones hit the Saudi tanker Encelia and targeted the Layla in the Red Sea, five Saudi tankers reversed course, and the IRGC says a tanker caught fire in a mined route south of Hormuz. The rates complex followed: the 10Y closed 4.6932% — its highest close of the war and a SECOND consecutive close above the 4.65% Stage-4 leg — and the 30Y closed 5.1595%, leaving 4.1 bp to its 5.20% leg (intraday 5.1732%, 2.7 bp). MOVE closed 80.08, the first 80-handle since 20 May on a fifth consecutive rise, and VIX snapped back to 18.70 — equities are joining. AAA gasoline printed $4.72 (22 Jul) — a seventh consecutive rise, 3 cents from the political→5 trigger. The lone easing gauge: 5Y5Y closed 2.1995%, back below the 2.20% line after three closes above. Asia LNG printed FRESH at ¥3,601, a new war-era record (+115.8%). A twelfth consecutive night of strikes; Rubio says Iran is ‘paying the price’; Trump warns of a ‘massive attack’ if Iran fails to negotiate; the 10-day framework remains tabled, unaccepted. No trigger fired on a confirmed close, so no channel moved — but oil→3 (74c), political→5 (3c) and Stage-4 Threshold B (4.1 bp) all now sit inside ONE normal session's move. Both event channels remain maxed — the hold is an artifact of the scale. Sequencing 25 → 25 → 25.",

    "tape": {
        "note": "24 Jul 2026 readings are intraday prints; 23 Jul and earlier are final closes (restated continuation series; front-month CO2/CL2). d/d deltas are 24 Jul intraday vs 23 Jul close; w/w deltas are vs 17 Jul close.",
        "oilGasHeader": ["Benchmark", "Intraday 24 Jul", "Δ d/d", "Δ vs pre-war close (27 Feb)", "BBG ticker"],
        "oilGas": [
            ["Brent front-month", "$93.49 /bbl (H 94.49 / L 93.41)", "–$0.77 (+$7.17 w/w)", "from $72.48 (+29.0%) — ~$21.0/bbl premium; easing off a 23 Jul high of $95.30 that pierced the $95 oil→3 trigger level; active COA prints $100.00", "CO2 Comdty (Close)"],
            ["Brent · 23 Jul close (final)", "$94.26 /bbl (+$3.10 vs my 23 Jul intraday $91.16)", "+$4.08 d/d — largest daily gain since early June; first $94-handle close since 4 Jun", "74 cents below the $95 trigger on a close basis; the intraday high $95.30 was through the level but the close was not", "CO2 Comdty"],
            ["WTI front-month", "$86.25 /bbl", "–$0.76 (+$4.47 w/w)", "from $67.02 (+28.7%) — the CL2 artifact narrowed: the 23 Jul CL2 close $87.01 vs active CLA $92.19; CLA prints $91.49 intraday", "CL2 Comdty"],
            ["Brent–WTI spread", "$7.24 /bbl", "widened", "~$8.5 on the active contracts", "derived"],
            ["Henry Hub natural gas", "$2.907 /MMBtu", "–$0.009 (–$0.00 w/w)", "from $3.06 (–5.1%) — US gas BELOW pre-war; not Hormuz-exposed", "NGA Comdty"],
            ["TTF Dutch gas (active)", "€61.96 /MWh", "+€0.06 (+€4.57 w/w)", "from €31.23 (+98.4%) — eased off the record €62.54 close; the 23 Jul close €61.90 sits just under the doubling line", "TZTA Comdty"],
            ["Japan/Asia LNG (23 Jul close — FRESH print)", "¥3,601", "+¥102 vs 22 Jul", "from ¥1,669 (+115.8%) — a NEW war-era record, the second in two sessions; no 24 Jul print (flagged, not carried)", "JGLA Comdty"],
        ],
        "ustNote": "24 Jul 2026 yields are intraday. d/d deltas are vs the 23 Jul close; w/w vs 17 Jul. The 10Y Stage-4 leg has now held above its line for TWO consecutive closes (4.6545%, 4.6932%); the 30Y leg is 4.1 bp away on a close basis and is the sole binding constraint.",
        "ustHeader": ["Tenor", "Yield (%) — intraday 24 Jul", "Δ d/d (bp)", "Δ w/w (bp)", "Δ vs pre-war (bp)", "BBG ticker"],
        "ust": [
            ["2-year UST", "4.35", "+0.5", "+17.5", "+98 (from 3.37%)", "USGG2YR Index"],
            ["5-year UST", "4.46", "+0.4", "+17.8", "+95 (from 3.50%)", "USGG5YR Index"],
            ["10-year UST", "4.70", "+0.8", "+15.4", "+76 (from 3.94%) — 23 Jul close 4.6932%, the HIGHEST close of the war; a second consecutive close above the 4.65% Stage-4 leg — now sustained", "USGG10YR Index"],
            ["30-year UST", "5.17", "+1.4", "+10.4", "+56 (from 4.61%) — 23 Jul close 5.1595%, highest since 19 May; 4.1 bp below the 5.20% Stage-4 leg (intraday 5.1732%, 2.7 bp)", "USGG30YR Index"],
            ["2s10s spread", "+35 bp", "+0.3", "–1.7", "–21 (flatter)", "USYC2Y10 Index"],
            ["10Y breakeven inflation", "2.264 (lagged; 23 Jul close)", "–1.8 (at close)", "—", "+0.7 (from 2.257%) — a third close above the pre-war anchor, but easing", "USGGBE10 Index"],
            ["5Y5Y forward inflation", "2.20", "+0.4", "+0.8", "+6.2 (from 2.14%) — the 23 Jul close 2.1995% fell BACK BELOW the 2.20% line after three closes above; 10.0 bp below the →5 trigger; the lone easing gauge", "USGG5Y5Y Index"],
            ["SOFR (lagged print, 22 Jul)", "3.62", "—", "—", "series lags", "SOFRRATE Index"],
        ],
        "crossHeader": ["Gauge", "Latest", "As of", "Δ vs pre-war", "Interpretation"],
        "cross": [
            ["DXY", "101.38", "24 Jul intraday", "+3.77 (from 97.61)", "Rangebound ~101 — marginally softer d/d; still no haven bid; the dollar is not the stress valve."],
            ["MOVE", "80.08", "23 Jul close (24 Jul lagged)", "+6.70 (from 73.38)", "First 80-handle since 20 May, on a FIFTH consecutive rise (70.88 → 80.08) — the fastest ascent since April. Both Treasury-downgrade legs now fail at the widest margin of the war."],
            ["VIX", "18.70", "23 Jul close (24 Jul lagged)", "–1.16 (from 19.86)", "SNAPPED BACK +2.06 (16.64 → 18.70) on the tanker attacks — the first sign that equities are joining; the rates/equity divergence narrowed."],
            ["AAA gasoline", "$4.72 /gal", "22 Jul print (latest; 23–24 Jul pending)", "+$1.20 (from $3.52, +34%)", "The political-stress reference (pre-war $3.52, peak $5.18). Seventh consecutive rise; 3 cents below the $4.75 threshold — the next confirmed print lands at or through it at the recent 3–5c pace."],
            ["DOE gasoline", "$4.001 /gal", "20 Jul weekly print", "~+$1.06 (from ~$2.94, +36%)", "First $4-handle since 15 Jun; next weekly print lands Monday 27 Jul."],
        ],
        "gasChartNote": "AUTMUSAG (AAA all-grades retail pump, daily) is the political-stress score reference (pre-war $3.52, peak $5.18, latest $4.72 on 22 Jul); USRFRUSA (DOE regular-grade retail spot, weekly) is the complementary gauge (pre-war ~$2.94, peak $4.50, latest $4.001 on 20 Jul). The AAA series has risen in seven consecutive prints and sits 3 cents from the $4.75 political→5 threshold; the 23–24 Jul prints are pending and the next lands at or through the trigger at the recent pace — the channel is evaluated on confirmed prints only, so the score holds until the data lands.",
        "straitHeader": ["Indicator", "Current reading", "Source"],
        "strait": [
            ["Strait closed · day ~146", "Closed to commercial traffic (blockade regime since 28 Feb war start); US naval blockade plus escort operation (~900 escorted transits, ~450m bbl since early May, per CENTCOM); Iran conditions transit on its own coordination and fees. Transits ~17% of typical (15 vs 88/day, 19 Jul count); 425 anchored (basis revised from 443–444); 74 tankers AIS-dark in 24h vs a 53.2 7-day average; war-risk ~8×, VLCC ~$2.5m; six P&I clubs withdrawn; all 9 major carriers suspended, limited or rerouting via the Cape.", "CENTCOM / straits.live / Windward"],
            ["Twelfth consecutive night of US strikes + mined-route incident", "CENTCOM strikes on 23 Jul hit maritime capabilities, missile and drone storage, coastal surveillance and air-defence assets across western and central Iran, including near Bushehr. Rubio: Iran is ‘paying the price’; Trump warns of a ‘massive attack’ if Iran fails to negotiate. The IRGC says a tanker caught fire in a ‘mined route’ south of the Strait (Tier 3, partially corroborated); the UK withdrew embassy staff.", "CENTCOM / CNN / Irish Times / UK FCDO"],
            ["Houthi embargo TURNS KINETIC — first hits on Saudi tankers", "Missiles and drones hit the Saudi tanker Encelia (bow fire; crew safe) and targeted the Layla in the Red Sea on 23 Jul — the first attacks executed under the embargo of Saudi ports. Five Saudi tankers reversed course 21 Jul, four toward Suez; Kpler had put ~75% of Saudi crude exports through Yanbu. ANZ: ‘a serious escalation’; Goldman sees $120+ Brent by Q4 if disruptions persist.", "The National / WaPo / Bloomberg / NBC"],
            ["Mediation — ceasefire still tabled, unaccepted", "The Qatar/Egypt/Pakistan/Oman 10-day framework remains received and unaccepted; rhetoric hardened this session; no venue or date named — the decision window is still described as days.", "Axios / CNBC / Irish Times"],
        ],
    },

    "analysis": {
        "intro": "The US economic shock holds at 25/30, but the 23 Jul session compressed every remaining distance at once: Brent's intraday high pierced the $95 trigger level before a $94.26 close (74 cents short), the 10Y put in the highest close of the war and its second consecutive close above the 4.65% Stage-4 leg, the 30Y closed 4.1 bp from the last Stage-4 leg, MOVE printed its first 80-handle since 20 May, and the AAA gasoline print landed 3 cents from the political→5 trigger. Nothing crossed a scoring trigger on a confirmed close, so no channel moved — but three separate triggers (oil, political, Stage-4 B) now sit inside one normal session's move, and the catalyst that produced the session — the Houthi embargo turning kinetic against Saudi tankers — is aimed directly at the bypass architecture that has kept oil at 2/5. The lone easing gauge was 5Y5Y, which slipped back below the 2.20% line.",
        "bondYieldNote": "24 Jul yields are intraday; d/d vs 23 Jul close, w/w vs 17 Jul. No channel moved; score held at 25.",
        "bondYield": [
            {"title": "(i) Treasury — held at 5; the downgrade condition fails at the widest margin of the war.", "text": "The 30Y closed 23 Jul at 5.1595% — highest since 19 May — with the cushion above the 5.00% downgrade leg widening 14.5 → 16 bp; and MOVE closed 80.08, a fifth consecutive rise and the first 80-handle since 20 May. The hold is fully fundamentals-based: term premium, supply concession into next week's FOMC (28–29 Jul), and a war-risk premium re-building on the Red Sea escalation. The intraday 30Y prints 5.1732% — 2.7 bp below the Stage-4 leg."},
            {"title": "(ii) Inflation anchor — held at 4; the advance reversed at the line.", "text": "5Y5Y closed 2.1995% — back below the 2.20% line after three consecutive closes above it — and prints 2.2035% intraday. The 10Y breakeven closed 2.2637%, a third consecutive close above the pre-war anchor but easing (–1.8 bp). The 2.30% →5 trigger is 10.0 bp away on a close basis — the distance WIDENED this session, the only one on the board that did. Whether this is consolidation or a top is the week's inflation question; the downgrade (a sustained move to the 2.142% anchor) remains far."},
            {"title": "(iii) Oil — held at 2 by 74 cents.", "text": "The 23 Jul close $94.26 is the first $94-handle close since 4 Jun and the largest daily gain since early June (+$4.08); the intraday high $95.30 was THROUGH the $95 trigger level, but the close was not, and the channel moves on confirmed closes only — one close above $95 would still need a second to satisfy ‘sustained’. The ACTIVE contract closed $100.69, the first triple-digit close on the unscored board since 22 May, and prints $100.00 this morning. The cause is structural, not headline froth: the Houthi embargo is now shooting at the tankers that carry the Saudi bypass volumes — the Encelia hit and the five course reversals put the ~75%-via-Yanbu flow directly at risk — while the IRGC's mined-route claim (Tier 3) pressures the Hormuz escort lane itself. Today's intraday tape has eased to $93.49; a settle near here keeps the trigger un-fired into Monday. (The CL2 WTI artifact narrowed: CL2 closed $87.01 vs the active CLA $92.19; WTI levels are still read off the active board.)"},
        ],
        "stage4Note": "Stage 4 is a credit/auction event. The 10Y leg of Threshold B is now sustained; the 30Y leg is the last one standing, 4.1 bp away.",
        "stage4": [
            {"title": "Threshold A · 13 May 30Y auction.", "text": "Historical. Cleared at 5.050%; the 9 Jul re-opening cleared 5.06% with a 0.3 bp stop-through. With the 30Y closing 5.1595% and rising, any long-duration supply now prices well above both — and next week's FOMC (28–29 Jul; markets price ~80% no-change) is the macro overlay."},
            {"title": "Threshold B · 30Y above 5.20% with 10Y above 4.65%.", "text": "The 10Y leg is SUSTAINED — two consecutive closes above the line (4.6545%, 4.6932%, the latter the war's highest), with the intraday at 4.7015%. The 30Y closed 5.1595%, 4.1 bp below its leg (23 Jul: 5.5 bp; now 4.1), and prints 5.1732% intraday — 2.7 bp below. At the past week's ~1–2 bp/session long-end drift the gap is a matter of sessions, and the catalysts are stacked: FOMC Tuesday–Wednesday, any long-duration supply, or one more risk-off session like 23 Jul. B tripping is the score's bridge toward the systemic scenarios."},
            {"title": "Threshold C · MOVE above 130.", "text": "Still far — but closing fastest. MOVE 80.08 is a fifth consecutive rise and the highest print since 20 May; the +3.77 jump on 23 Jul was the largest of the sequence. VIX joined at 18.70 (+2.06) — the vol repricing is no longer rates-only."},
        ],
        "crossAsset": "The repricing broadened this session — levels first, rates vol second, and now the first equity-vol response: VIX snapped back to 18.70 on the tanker attacks while MOVE printed an 80-handle. The dollar stayed flat at ~101 — still no haven bid, which keeps the stress reading in rates and energy rather than in a flight-to-quality. The gas complex stayed at records: Asia LNG's fresh ¥3,601 print is a new war-era high (+115.8%), TTF eased to €61.90 just under its doubling line, and US Henry Hub sits 5.1% BELOW pre-war — the signature of a Hormuz/LNG-routing shock, not a global-energy shock, fully intact. The cross-asset risk is no longer hypothetical geography: the embargoed Yanbu outlet that carried ~75% of Saudi exports is now under fire, and a hit on a laden VLCC or on terminal infrastructure would move crude, breakevens and bond vol together, at full amplitude.",
    },

    "channels": [
        {"name": "Maritime denial", "score": 5, "state": "max", "rationale": "Held at 5 (max). Strait closed to commercial traffic; transits ~17% of typical; 425 ships anchored; 74 tankers AIS-dark in 24h vs a 53.2 average; six P&I; clubs withdrawn; all 9 major carriers suspended or rerouting; the embargo now extends the denial regime to Saudi Red Sea ports by force. No verified reopening.", "upgrade": "at max.", "downgrade": "verified reopening (escorted convoys) with traffic above 25% of normal for 10 sessions → to 3–4."},
        {"name": "Oil price shock", "score": 2, "state": "hold", "rationale": "Held at 2 — by 74 cents. The 23 Jul close $94.26 (+$4.08, largest daily gain since early June; first $94-handle since 4 Jun); the intraday high $95.30 pierced the trigger level but the close did not; the ACTIVE contract closed $100.69. Confirmed closes only, and ‘sustained’ needs a second close.", "upgrade": "Brent above $95 sustained → to 3.", "downgrade": "mediated pause + close back at/below the $72.48 anchor → to 1."},
        {"name": "US inflation impulse", "score": 4, "state": "hold", "rationale": "Held at 4. 5Y5Y closed 2.1995% — back below the 2.20% line after three closes above; intraday 2.2035%. 10Y BE closed above its pre-war anchor a third time but eased (2.264%). 10.0 bp below the →5 trigger — the only distance on the board that widened this session.", "upgrade": "5Y5Y sustained above 2.30% → to 5.", "downgrade": "5Y5Y sustained at/below the 2.142% pre-war anchor → to 3."},
        {"name": "Treasury stress", "score": 5, "state": "max", "rationale": "Held at 5 — fundamentals-held at the widest margin of the war. 30Y closed 5.1595% (highest since 19 May), 16 bp above the 5.00% leg; MOVE 80.08, first 80-handle since 20 May on a fifth straight rise. Both downgrade legs fail simultaneously and the failure is deepening.", "upgrade": "at max.", "downgrade": "30Y close under 5.00% with MOVE under 75 sustained → to 4."},
        {"name": "Political stress", "score": 4, "state": "hold", "rationale": "Held at 4 — one print from the trigger. AAA $4.72 (22 Jul print, latest confirmed) — seventh consecutive rise, 3c below $4.75; DOE weekly $4.001. The 23–24 Jul prints are pending. At the recent 3–5c pace the next print lands at or through the threshold. Evaluated on confirmed prints only.", "upgrade": "gasoline above $4.75 sustained → to 5.", "downgrade": "toward the $3.52 pre-war level → to 3."},
        {"name": "Escalation risk", "score": 5, "state": "max", "rationale": "Held at 5 (max). Twelfth consecutive night of US strikes; the Houthi embargo turned kinetic against Saudi tankers; a mined-route tanker fire south of Hormuz; Rubio's ‘paying the price’ and Trump's ‘massive attack’ warning; the ceasefire framework remains unaccepted with no venue or date named.", "upgrade": "at max.", "downgrade": "mediated stand-down + talks resume → to 4–3."},
    ],
    "scoreTotal": "CRISIS band — eighth session at 25, with three triggers inside one session's move: political →5 is 3c away on a pending print, oil →3 is 74c on a close basis (intraday already pierced; active board through $100), Stage-4 B is 4.1 bp on its last leg. US-inflation →5 widened to 10.0 bp. With both event channels maxed, only market channels can move the score.",

    "whatsChanged": {
        "title": "4 · What's changed since the last edition (23 Jul → 24 Jul AM)",
        "items": [
            "Score holds at 25/30 for an eighth session — through the war's most violent repricing day in seven weeks. No channel moved; three triggers now sit inside one session's move. Source: Bloomberg.",
            "The Houthi embargo turned kinetic. Missiles and drones hit the Saudi tanker Encelia (bow fire; crew safe) and targeted the Layla in the Red Sea on 23 Jul — the first executed attacks under the embargo of Saudi ports; five Saudi tankers had already reversed course. The route that carried ~75% of Saudi crude exports in early July is now under fire. Source: The National / Washington Post / Bloomberg.",
            "Brent pierced $95 intraday and closed $94.26 — 74 cents from the trigger. The +$4.08 close-to-close gain was the largest since early June; the active COA closed $100.69, the first triple-digit close on the unscored board since 22 May, and Goldman now sees $120+ by Q4 if disruptions persist. Source: Bloomberg / The National.",
            "The 10Y put in the highest close of the war; the 30Y is 4.1 bp from completing Threshold B. 10Y 4.6932% — a second consecutive close above the 4.65% leg, making it sustained; 30Y 5.1595% (intraday 5.1732%, 2.7 bp below the 5.20% leg). Source: Bloomberg.",
            "The vol complex broadened: MOVE 80.08, VIX snapped +2.06 to 18.70. First MOVE 80-handle since 20 May, fifth straight rise; the first meaningful equity-vol response of the month. Source: Bloomberg.",
            "5Y5Y slipped back below 2.20% — the lone easing gauge. Closed 2.1995% after three closes above the line; the →5 distance widened to 10.0 bp. Source: Bloomberg.",
            "Asia LNG set a second consecutive war-era record. Fresh 23 Jul print ¥3,601 (+115.8% vs pre-war); TTF eased to €61.90, just under its doubling line. Source: Bloomberg.",
            "Gasoline: a seventh consecutive rise, 3 cents from the trigger. The 22 Jul AAA print landed at $4.72; the 23–24 Jul prints are pending. Source: AAA / Bloomberg.",
        ],
    },

    "scenarios": [
        {"name": "Return to full war", "p": 38, "desc": "The modal path: a twelfth night of strikes, hardened rhetoric on both sides (‘paying the price’; the massive-attack warning), the ceasefire unaccepted with no venue or date, and the Houthis now executing attacks rather than declaring them.", "path": "Brent $105–140; MOVE above 90; oil to 3–4, political to 5, US-inflation to 5; score 28–30."},
        {"name": "Contained but violent — blockaded stalemate", "p": 21, "desc": "Strikes continue but stay off major energy infrastructure; escort-only transits; the bypass pipelines keep capping crude. Eroding fastest: the embargo is now shooting at the bypass tankers, the front-month closed $94.26 and the active board is through $100.", "path": "Brent $88–96; MOVE 76–86; risk premium $18–26/bbl; score 25–26 as political→5 lands."},
        {"name": "Deal collapse — MoU formally lapses", "p": 20, "desc": "The ceasefire proposal is rejected or expires; sanctions harden; the strait stays shut; fighting persists at high intensity without full-war targeting.", "path": "Brent $92–108; oil to 3; 30Y above 5.20% with the 10Y leg already sustained (Stage-4 B trips); score 26–27."},
        {"name": "Regional relapse — Gulf energy infrastructure hit", "p": 12, "desc": "Iran or the Houthis escalate from tankers to terminals: Yanbu, the East–West pipeline, Abqaiq/Ras Tanura or Fujairah. The first tanker hits under the embargo make this the best-armed tail in the map — the remaining step is from ship to shore.", "path": "Brent $150+; emergency policy; HY spreads above 500 bp; score 29–30."},
        {"name": "Mediated pause — the 10-day ceasefire sticks", "p": 9, "desc": "Washington and Tehran accept the Qatar/Egypt/Pakistan/Oman framework; strikes halt, both lanes reopen under the fee regime. Still formally live, but this session's rhetoric and the Red Sea escalation both cut against near-term acceptance.", "path": "Brent $74–86; MOVE under 70; Treasury→4, US-inflation→3, escalation→4; score falls toward 20–22."},
    ],
    "scenarioShift": "Probability shifts from the 23 Jul edition: regional relapse +2 (10→12) — the embargo moved from declaration to execution with the Encelia hit, and only the ship-to-shore step remains; contained-but-violent –2 (23→21) — the containment equilibrium now takes direct fire on its bypass leg; return to full war holds at 38 — rhetoric hardened but no strategic-target crossing yet; deal collapse holds at 20; mediated pause holds at 9 — the framework survives, unaccepted. Driver: the same 24 hours produced the war's largest oil repricing in seven weeks and its first executed attacks on Saudi shipping.",

    "watchlist": [
        "Political →5 ($4.75) — one print away. AAA confirmed at $4.72 (22 Jul), rising for seven straight prints; the 23–24 Jul prints are pending. A confirmed print at/above $4.75 takes the score to 26 — the first move off 25 in eight sessions. The DOE weekly lands Monday 27 Jul.",
        "Oil →3 ($95) — 74 cents on a close basis, already pierced intraday. Today's tape has eased to $93.49; a weekend of Red Sea headlines lands on Monday's open. One close above $95 starts the clock; a second confirms. The active board is already through $100 — the continuation series rolls toward it.",
        "Stage-4 Threshold B — the 30Y is the last leg, 4.1 bp (2.7 intraday). The 10Y leg is sustained. The FOMC meets Tuesday–Wednesday (28–29 Jul, ~80% priced for no change): a hawkish read, any long-duration supply, or one more 23 Jul-sized session trips it. B is the bridge from 25–26 toward the systemic scenarios.",
        "Ship-to-shore escalation in the Red Sea. The Encelia and Layla attacks put the embargo in execution; the tell to watch is a strike on a laden VLCC out of Yanbu or on terminal infrastructure — that is the regional-relapse trigger and it re-prices crude, breakevens and bond vol together.",
        "The ceasefire decision window — rhetoric moved against it. Rubio's ‘paying the price’ and the massive-attack warning cut against acceptance; the framework remains tabled with no venue or date. Acceptance is still the first downgrade path in weeks (escalation 5→4).",
        "US-inflation →5 (5Y5Y above 2.30% sustained) — 10.0 bp, and now the swing gauge. The pullback below 2.20% is the board's only easing signal; whether it is a top or a pause decides if the score's ceiling this fortnight is 26 or 28.",
        "Gas complex — second consecutive Asia LNG record. ¥3,601 on the fresh 23 Jul print; no 24 Jul print yet — verify, never carry. Watch Asian demand-rationing headlines into the weekend.",
    ],

    "sourceLog": {
        "tier1Market": "Bloomberg Terminal extract (US Iran BBG Data.xlsx, restated front-month continuation series). Tickers: CO2/CL2 Comdty (Brent/WTI front-month; the CL2 artifact narrowed this session — CL2 closed $87.01 vs active CLA $92.19; WTI is still read off the active board); COA/CLA Comdty (active, unscored, quoted for corroboration — COA closed $100.69, prints $100.00); NGA/TZTA/JGLA Comdty (JGLA printed FRESH 23 Jul at ¥3,601 — a new war-era record; no 24 Jul print); USGG2YR/5YR/10YR/20YR/30YR Index; USYC2Y10; USGGBE10 (23 Jul close 2.2637; 24 Jul lagged); USGG5Y5Y; SOFRRATE (lagged, 22 Jul); MOVE and VIX (23 Jul closes 80.08 / 18.70; 24 Jul lagged); DXY; AUTMUSAG (AAA pump — score reference; latest print 22 Jul $4.72; 23–24 Jul pending) and USRFRUSA (DOE regular spot, weekly — corroboration; 20 Jul print $4.001).",
        "tier1News": "CENTCOM via CNN / Irish Times (twelfth consecutive night of strikes; targets — maritime capabilities, missile and drone storage, coastal surveillance, air defences; Rubio remarks; the massive-attack warning), The National / Washington Post / Bloomberg / NBC (Houthi attacks on the Encelia and Layla; five Saudi tankers reversing course; ANZ and Goldman commentary — $120+ Q4 Brent if disruptions persist), Axios / CNBC (10-day ceasefire framework — received, unaccepted; mediator push), straits.live / Windward (day count, transits ~17% of typical on the 19 Jul count, 425 anchored on the revised basis, 74 AIS-dark in 24h vs 53.2 avg, 8× war-risk cover, six P&I; withdrawals, all-9-carrier disruption), Federal Reserve calendar (FOMC 28–29 Jul), UK FCDO (embassy staff withdrawal).",
        "tier3": "The IRGC claim that a tanker caught fire in a ‘mined route’ south of Hormuz is labelled Tier 3; it is partially corroborated by traffic-diversion data but no independent confirmation of mining is available, and it is not used for any scoring decision. IRNA, Mehr, Press TV used only with explicit role labels.",
    },

    "protocol": [
        {"step": "Refresh the Bloomberg extract", "detail": "Parse the latest dated row (24 Jul) as intraday; reclassify 23 Jul as a final close; re-map columns via the robust scan (front-month CO2/CL2; both gasoline series; JGLA checked fresh — printed 23 Jul ¥3,601, flagged rather than carried for 24 Jul; MOVE/VIX/BE10 24 Jul lagged, 23 Jul closes carried and labelled; SOFR lagged 22 Jul)."},
        {"step": "Recompute deltas", "detail": "d/d vs the 23 Jul close; w/w vs the close five trading sessions back (17 Jul this edition); vs-pre-war vs the 27 Feb 2026 anchor (re-verified, unchanged)."},
        {"step": "Re-evaluate the six channels", "detail": "Market channels move on confirmed closes only — all held: oil 2 (close $94.26, under $95 despite the $95.30 intraday high); Treasury 5 (30Y 5.1595% above 5.00%; MOVE 80.08 above 75); US-inflation 4 (5Y5Y 2.1995%, under 2.30%); political 4 (AAA $4.72 confirmed, under $4.75). Maritime/escalation event-based, both maxed."},
        {"step": "Reconcile against the prior edition", "detail": "The US session marked up violently through the Asia snapshot: Brent 23 Jul intraday $91.16 → close $94.26 (+$3.10, the second-largest gap of the war); 10Y 4.6505% → 4.6932% (+4.3 bp); 30Y 5.1396% → 5.1595% (+2.0 bp); TTF €62.90 → €61.90 close (–€1.00); 5Y5Y 2.2177% → 2.1995% (–1.8 bp); MOVE 76.31 (carried) → 80.08 close."},
        {"step": "Update scenarios and watchlist", "detail": "Re-rank catalysts: political→5 (one pending print, 3c), oil→3 (74c on a close basis; pierced intraday; active board through $100), Stage-4 B (30Y last leg, 4.1 bp; FOMC 28–29 Jul), US-inflation→5 (10.0 bp, widened); regional relapse 10→12 on the executed tanker attacks; full war holds 38% modal."},
    ],

    "methodology": {
        "scale": "Six transmission channels (maritime denial, oil price shock, US inflation impulse, Treasury stress, political stress, escalation risk), each 0–5, summed to 0–30. Bands: 0–7 watch · 8–14 stress · 15–21 systemic-risk watch · 22–30 crisis. Market/economic channels move only on a confirmed close through a trigger; escalation-risk is event-based. Hysteresis note: upgrades fire on a sustained break; downgrades only on a sustained reversal past a wider threshold — deliberately, to avoid whipsawing. Treasury (5) was held through 15–17 Jul on hysteresis when MOVE fell below 75; as of the 23 Jul close both downgrade legs fail at the widest margin of the war (30Y 5.1595% vs the 5.00% leg; MOVE 80.08 vs the 75 leg) — the hold is fully fundamentals-based. The same discipline held oil at 2 this session: the intraday high pierced $95 but the close did not, and a first close above $95 would still need a second to satisfy ‘sustained’. Scale cap: maritime and escalation are both at 5/5, so further geopolitical deterioration — including the executed tanker attacks and the mined-route incident — cannot raise the score; only the four market channels can. A flat 25 must not be read as stability.",
        "gasoline": "Political-stress is scored on AUTMUSAG (AAA all-grades retail pump; pre-war $3.52, peak $5.18, latest confirmed print $4.72 on 22 Jul — a seventh consecutive rise) for continuity; the 23–24 Jul prints are pending in the extract and the channel holds until they are confirmed. USRFRUSA (DOE regular-grade retail spot; pre-war ~$2.94, peak $4.50, latest $4.001 on 20 Jul; next print Monday 27 Jul) is tracked alongside. See the chart in section 1.",
        "anchor": "Brent $72.48; WTI $67.02; 2Y 3.375%; 5Y 3.502%; 10Y 3.938%; 30Y 4.611%; 2s10s +55.64 bp; 5Y5Y 2.142%; 10Y BE 2.257%; MOVE 73.38; VIX 19.86; DXY 97.608; gasoline (AAA) $3.52; Henry Hub $3.06; TTF €31.23; Asia LNG ¥1,669. (Re-verified — unchanged.) Brent +29.0%, WTI +28.7%, TTF +98.4%, Asia LNG +115.8%; the 30Y (+56 bp), 10Y (+76 bp), 5Y5Y (+6.2 bp), 10Y BE (+0.7 bp), MOVE (+6.70) and DXY (+3.77) all sit above their anchors; VIX and US Henry Hub remain below pre-war — though VIX's +2.06 snap on the tanker attacks is the first sign of the equity complex joining.",
        "intraday": "The latest dated row is a Singapore-AM intraday snapshot; US-hours trading and headlines set the close (recent reconciliation gaps on Brent: +$4.01, +$2.46, –$0.90, +$1.91, +$0.60, +$3.10 — the 23 Jul gap was the second-largest of the war). The CL2 WTI series remains flagged as a data artifact against the active CLA contract, though the gap narrowed this session; WTI levels are read off the active board pending resolution. Market-channel triggers are evaluated on confirmed closes; escalation-risk is event-based. Absolute levels use the restated continuation series and are not directly comparable with pre-restatement editions, though the directional analysis is continuous.",
    },
}

with open("editions.json", "w") as f:
    json.dump(EDITIONS, f, indent=2, ensure_ascii=False)

print("Wrote editions.json with full sections for:", list(EDITIONS.keys()))
