#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Source of truth for editions.json — the two-edition toggle on the dashboard.

Holds the FULL section-by-section content of the two most recent editions as
Python literals, copied from that edition's PDF build script. Edit the ed*_block
files, never editions.json. Keep exactly two dates: when a new edition is added,
drop the oldest block from the import list below.

Run:  python3 generate_editions.py
"""
import json

EDITIONS = {}

# =====================================================================
# 1 SEPTEMBER 2026
# ---------------------------------------------------------------------
# NOTE: 28 August was dropped from the toggle on 2 September, per the
# two-editions-only rule. It remains fully present in the archive table
# and the score-history chart (edition PDF + annex, both downloadable),
# and ed28_block.py stays on disk unimported.
# 31 August is still absent from the toggle and the reason stands: the
# 31 Aug PDF build used UNSUFFIXED fragment names and the 1 Sep build
# overwrote them, so its tape and analysis sections have no surviving
# source. Rebuild it here only from a real source, never from OCR.
# From the 2 September build every fragment is DATE-SUFFIXED, so this
# cannot recur.
# =====================================================================
# 1 September was dropped from the toggle on 3 September, per the
# two-editions-only rule. It remains fully present in the archive table and
# the score-history chart, and ed01sep_block.py stays on disk unimported.

# =====================================================================
# 4 September was dropped from the toggle on 8 September, per the
# two-editions-only rule. It remains fully present in the archive table and
# the score-history chart, and ed04sep_block.py stays on disk unimported.

# =====================================================================
# 7 SEPTEMBER 2026
# ---------------------------------------------------------------------
# ed07sep_block.py is GENERATED by build/tools/make_edition_block.py from
# that day's PDF build fragments -- do not hand-edit it, regenerate it.
# 3 September was dropped from the toggle on 7 September, per the
# two-editions-only rule. It remains fully present in the archive table and
# the score-history chart, and ed03sep_block.py stays on disk unimported.
# =====================================================================
# ed07sep_block.py stays on disk unimported: the toggle holds two editions only.

# =====================================================================
# 8 SEPTEMBER 2026
# ---------------------------------------------------------------------
# ed08sep_block.py is GENERATED by build/tools/make_edition_block.py from
# that day's PDF build fragments -- do not hand-edit it, regenerate it.
# =====================================================================
# 8 September was dropped from the toggle on 10 September, per the
# two-editions-only rule. It remains fully present in the archive table and
# the score-history chart, and ed08sep_block.py stays on disk unimported.

# ed09sep_block.py is GENERATED by build/tools/make_edition_block.py from the
# day's build/ed_*.py fragments -- never hand-copied. Adding 9 Sep drops 7 Sep
# from the toggle; it stays in the archive table and the score-history chart,
# and ed07sep_block.py stays on disk unimported.
# 9 September was dropped from the toggle on 11 September, per the
# two-editions-only rule. It remains fully present in the archive table and the
# score-history chart, and ed09sep_block.py stays on disk unimported.

# =====================================================================
# 10 SEPTEMBER 2026
# =====================================================================
from ed10sep_block import ED10SEP
EDITIONS['2026-09-10'] = ED10SEP

# =====================================================================
# 11 SEPTEMBER 2026 -- THE SCORE MOVES, 27/30 to 28/30
# ---------------------------------------------------------------------
# ed11sep_block.py is GENERATED by build/tools/make_edition_block.py from the
# day's build/ed_*.py fragments -- never hand-copied. Adding 11 Sep drops 9 Sep
# from the toggle.
# =====================================================================
from ed11sep_block import ED11SEP
EDITIONS['2026-09-11'] = ED11SEP


with open("editions.json", "w") as f:
    json.dump(EDITIONS, f, indent=2, ensure_ascii=False)

print("Wrote editions.json with full sections for:", list(EDITIONS.keys()))
